# Generated by Django 3.1.3 on 2021-08-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=6),
        ),
    ]
