# Generated by Django 3.1.3 on 2021-08-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='address',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
