# Generated by Django 3.1.3 on 2021-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adminhod_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
