# Generated by Django 3.1.3 on 2021-08-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_adminhod_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.course'),
        ),
    ]
