# Generated by Django 3.1.3 on 2021-08-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210817_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavestudentreport',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
