# Generated by Django 3.1.3 on 2021-08-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210818_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavestudentreport',
            old_name='subject_id',
            new_name='student_id',
        ),
    ]
