# Generated by Django 3.1.3 on 2021-08-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210818_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admin',
            new_name='student',
        ),
    ]
