# Generated by Django 3.1.3 on 2021-08-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210818_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='admin',
        ),
    ]
