# Generated by Django 3.1.3 on 2021-08-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210818_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavestudentreport',
            name='status',
            field=models.CharField(choices=[('Aprove', 'Aprove'), ('Reject', 'Reject'), ('Panding', 'Panding')], default='Panding', max_length=7),
        ),
    ]
